### PR TITLE
dkregistry: remove tokio-core, use tokio instead

### PR DESCRIPTION
**Pull request by steveeJ**
@lucab PTAL and let me know if I'm missing something or if the handle is indeed unused

### CODE REVIEW

**Comment by lucab** [comment]
We can remove it, I think it was required by the previous hyper async API. Can we fully drop `tokio-core` from cargo manifest after this rework?

**Comment by steveeJ** [comment]
> Can we fully drop `tokio-core` from cargo manifest after this rework?

After changing the occurrences in all examples etc I believe we can. Since you agree I'm going to proceed and we'll find out for sure.

**Comment by lucab** [comment]
@steveeJ yes, please. And thanks a lot for the rework!

**Comment by lucab** [comment]
@steveeJ any plan to finish this? I have some other cincinnati changes that may benefit from it.

**Comment by lucab** [comment]
I pushed forward the changes in your second commit, using `tokio` runtime instead and completely dropping `tokio-core`. Travis is green and LGTM. Please have a last look and merge if ok.

**Comment by steveeJ** [comment]
> I pushed forward the changes in your second commit, using `tokio` runtime instead and completely dropping `tokio-core`. Travis is green and LGTM. Please have a last look and merge if ok.

Nice, thanks for picking this one up! I had another look and couldn't spot any issues.

**Pull request merged**
