### PR TITLE
tests/quay: test authenticated methods

### PR DESCRIPTION
**Pull request by lucab**
Add a login test for quay.io. Credentials for a dedicated CI user
are set up on travis.

### CODE REVIEW

**Comment by lucab** [comment]
Uhm, this worked on `master` but this PR is not seeing user/passwd vars.

@steveeJ it's a free "dkregistry" user on quay/dockerhub. It doesn't have any repo but we can grant read access to existing private ones.

**Comment by steveeJ** [comment]
> Uhm, this worked on `master` but this PR is not seeing user/passwd vars.
Probably some deeply hidden travis setting.

> it's a free "dkregistry" user on quay/dockerhub. It doesn't have any repo but we can grant read access to existing private ones.

I granted that user read access to *steveej/cincinnati-test* which will be available for the time being.

**Comment by lucab** [comment]
@steveeJ changed to use your pull-secrets. This covers login+tags+manifest right now. We can land it first and add more things later, or I can add a few more here, as you prefer.

**Comment by lucab** [comment]
This now also covers fetching the blob from a single-layer private image, PTAL.

**Pull request merged**
