### PR TITLE
Release 0.3.0

### PR DESCRIPTION
**Pull request by lucab**
Relevant changes:
 * dkregistry: remove tokio-core, use tokio instead
 * client: add an ensure_v2 helper
 * blobs: switch from hyper to reqwest
 * lib/get_credentials: include unfound index in error message
 * manifest/v2s1: add `get_labels()` method, test and example
 * dkregistry: format with 1.31.0 toolchain
 * cargo/maintainers: add Stefan Junker

### CODE REVIEW

**Comment by steveeJ** [comment]
Any chance you verified the validity of #56?

**Comment by steveeJ** [comment]
We should get #82 into this release.

**Comment by lucab** [comment]
Rebased to include #82. The first commit in the series is equivalent to https://github.com/camallo/dkregistry-rs/pull/56. We should have done that when we actually did the API break, I can split it out of this release PR if you prefer for clarity.

**Comment by steveeJ** [comment]
> The first commit in the series is equivalent to #56.

That PR adds a new environment variable and doesn't do a version bump. Where's the equivalence? :mag:

**Comment by lucab** [comment]
I'm closing this for now as we are piling up a few more bits. I'll trigger another release attempt once PR queue is drained again.

**Pull request closed without merging**
