### PR TITLE
Release 0.2.1

### PR DESCRIPTION
**Pull request by steveeJ**
Bump version to 0.2.0 manually in order to use `cargo release patch` for a semi-automatic release.

@lucab do you usually edit the commit message generated by `cargo release`?

Depends on #52.

### CODE REVIEW

**Comment by steveeJ** [comment]
Cool, thanks! Let me rebase this on top of #52 so I get a hang of the process.

**Comment by steveeJ** [comment]
I've created https://github.com/lucab/dkregistry-rs/pull/1 which modifies #52. After that's merged I'll rebase this on master and attempt a release according to the guide.

**Comment by lucab** [comment]
LGTM. Feel free to proceed with the release after a rebase (you probably need to re-adjust the tag as well).

**Comment by steveeJ** [comment]
I'm closing this as it's not according to the guide, which says to create the release branch on the upstream repo.

**Pull request closed without merging**
