### PR TITLE
docs: clarify licensing

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
This adds license files and information to the README.

Closes: #143

### CODE REVIEW

**Comment by lucab** [comment]
@LalatenduMohanty thank for the cleanups. However I think #143 is just asking us to make the license more prominent, not to relicense the whole crate (`MIT OR APL2` is fine, and better aligned with the larger Rust ecosystem).

I think you can follow the approach from other repos ([this](https://github.com/lucab/libsystemd-rs/tree/v0.2.1) is a personal example I have) and mirror it here, like this:
 * Add a snippet at the bottom of README
 * Add a COPYRIGHT file
 * A a LICENSE-MIT and LICENSE-APACHE-2.0

**Comment by LalatenduMohanty** [comment]
Thanks @lucab . It is interesting that Rust ecosystem prefers dual licensing.

**Comment by lucab** [comment]
@LalatenduMohanty that is documented in the [language guidelines](https://rust-lang.github.io/api-guidelines/necessities.html#crate-and-its-dependencies-have-a-permissive-license-c-permissive). It shouldn't really matter for Cincinnati, as the consumer can pick which of the two it prefers.

**Comment by LalatenduMohanty** [comment]
@lucab Thanks, I have updated the PR as per https://rust-lang.github.io/api-guidelines/necessities.html#crate-and-its-dependencies-have-a-permissive-license-c-permissive

**Pull request merged**
